/**
 * src/app/layout.tsx
 * Корневой layout App Router: общая HTML-обвязка, подключение глобальных стилей и шрифтов.
 */
import type { Metadata, Viewport } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header/Header';
import { MainNav } from '@/components/MainNav/MainNav';
import { ChatAssistantButton } from '@/components/ChatAssistantButton/ChatAssistantButton';
import { StyledComponentsRegistry } from '@/lib/StyledComponentsRegistry';
import { ApolloProviderWrapper } from '@/lib/apollo-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StyledComponentsRegistry>
          <ApolloProviderWrapper>
            <>
              <Header />
              <MainNav />
              {children}
              <ChatAssistantButton />
            </>
          </ApolloProviderWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
